//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicPortal.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить жанр.
        /// </summary>
        public static string AddGenre {
            get {
                return ResourceManager.GetString("AddGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить исполнителя.
        /// </summary>
        public static string AddPerformer {
            get {
                return ResourceManager.GetString("AddPerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить песню.
        /// </summary>
        public static string AddSong {
            get {
                return ResourceManager.GetString("AddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш браузер не поддерживает аудио элемент.
        /// </summary>
        public static string AudioAlert {
            get {
                return ResourceManager.GetString("AudioAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизовать.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По жанрам.
        /// </summary>
        public static string byGenre {
            get {
                return ResourceManager.GetString("byGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По названию.
        /// </summary>
        public static string byName {
            get {
                return ResourceManager.GetString("byName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По авторам.
        /// </summary>
        public static string byPerformer {
            get {
                return ResourceManager.GetString("byPerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл!.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите язык.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают!.
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деавторизовать.
        /// </summary>
        public static string Deauthorize {
            get {
                return ResourceManager.GetString("Deauthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с таким именем уже существует!.
        /// </summary>
        public static string FileExist {
            get {
                return ResourceManager.GetString("FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО.
        /// </summary>
        public static string FullNameInp {
            get {
                return ResourceManager.GetString("FullNameInp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО исполнителя.
        /// </summary>
        public static string FullnamePerformer {
            get {
                return ResourceManager.GetString("FullnamePerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлениие жанра.
        /// </summary>
        public static string GenreAddTitle {
            get {
                return ResourceManager.GetString("GenreAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение жанра.
        /// </summary>
        public static string GenreEditTitle {
            get {
                return ResourceManager.GetString("GenreEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог жанров.
        /// </summary>
        public static string GenreList {
            get {
                return ResourceManager.GetString("GenreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название жанра.
        /// </summary>
        public static string GenreName {
            get {
                return ResourceManager.GetString("GenreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы в режиме администратора.
        /// </summary>
        public static string InAdmin {
            get {
                return ResourceManager.GetString("InAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string LoginInp {
            get {
                return ResourceManager.GetString("LoginInp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль!.
        /// </summary>
        public static string LogPasInvalid {
            get {
                return ResourceManager.GetString("LogPasInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет аккаунта.
        /// </summary>
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вы не авторизованы.
        /// </summary>
        public static string NotAuthorize {
            get {
                return ResourceManager.GetString("NotAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        public static string PageLoginTitle {
            get {
                return ResourceManager.GetString("PageLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Музыкальный портал.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string PasswordInp {
            get {
                return ResourceManager.GetString("PasswordInp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотя бы одну заглавную букву и одну цифру!.
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать не менее 6 символов!.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string Performer {
            get {
                return ResourceManager.GetString("Performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлениие исполнителя.
        /// </summary>
        public static string PerformerAddTitle {
            get {
                return ResourceManager.GetString("PerformerAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение исполнителя.
        /// </summary>
        public static string PerformerEditTitle {
            get {
                return ResourceManager.GetString("PerformerEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог исполнителей.
        /// </summary>
        public static string PerformerList {
            get {
                return ResourceManager.GetString("PerformerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторить пароль.
        /// </summary>
        public static string RepPasswordInp {
            get {
                return ResourceManager.GetString("RepPasswordInp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не должно быть пустым!.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлениие песни.
        /// </summary>
        public static string SongAddTitle {
            get {
                return ResourceManager.GetString("SongAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение песни.
        /// </summary>
        public static string SongEditTitle {
            get {
                return ResourceManager.GetString("SongEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название песни.
        /// </summary>
        public static string SongTitle {
            get {
                return ResourceManager.GetString("SongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление пользователями.
        /// </summary>
        public static string UserControl {
            get {
                return ResourceManager.GetString("UserControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким логином уже существует!.
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть аккаунт.
        /// </summary>
        public static string YesAccount {
            get {
                return ResourceManager.GetString("YesAccount", resourceCulture);
            }
        }
    }
}
